// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiwEXUHgamQ1tV-f-IebwYFwBMTV7EbyE',
    appId: '1:749824273358:web:1a6fa3bf65a3218040199f',
    messagingSenderId: '749824273358',
    projectId: 'snap-friend-dev',
    authDomain: 'snap-friend-dev.firebaseapp.com',
    storageBucket: 'snap-friend-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5OYSmQdcIZ4ZDkLBv2q9jEielJYYz_w',
    appId: '1:749824273358:android:bd678396ed436b9140199f',
    messagingSenderId: '749824273358',
    projectId: 'snap-friend-dev',
    storageBucket: 'snap-friend-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRWV7xRs6JrhK919JJhhjpMcWUFeOJQ5Y',
    appId: '1:749824273358:ios:e85f85ac6f2971a640199f',
    messagingSenderId: '749824273358',
    projectId: 'snap-friend-dev',
    storageBucket: 'snap-friend-dev.firebasestorage.app',
    iosBundleId: 'com.example.snapFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRWV7xRs6JrhK919JJhhjpMcWUFeOJQ5Y',
    appId: '1:749824273358:ios:e85f85ac6f2971a640199f',
    messagingSenderId: '749824273358',
    projectId: 'snap-friend-dev',
    storageBucket: 'snap-friend-dev.firebasestorage.app',
    iosBundleId: 'com.example.snapFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiwEXUHgamQ1tV-f-IebwYFwBMTV7EbyE',
    appId: '1:749824273358:web:c8f1a74356bc726940199f',
    messagingSenderId: '749824273358',
    projectId: 'snap-friend-dev',
    authDomain: 'snap-friend-dev.firebaseapp.com',
    storageBucket: 'snap-friend-dev.firebasestorage.app',
  );
}
